# Import

In [1]:
import numpy as np
import random
from scipy.stats import spearmanr, pearsonr

#import the custom functions
import MFunctions as mf

In [2]:
#Load verb_symilarity which is the same for all
simdict = mf.verb_similarity("SimVerb-3500.txt")

# linear + quadratic (13 total)

In [3]:
# Make observables object
set1 = mf.observables(["Linear.txt","Quadratic.txt"])
# Load matrices and make vector dictionaries
objsubset1 = mf.vector_dictionary("matrices_1160_arg_obj_context_subj.txt",set1)
subobjset1 = mf.vector_dictionary("matrices_1160_arg_subj_context_obj.txt",set1,[0])
obj08sub02set1 = mf.vector_dictionary([["matrices_1160_arg_obj_context_subj.txt","matrices_1160_arg_subj_context_obj.txt"],[0.8,0.2]],set1,[1])
obj09sub01set1 = mf.vector_dictionary([["matrices_1160_arg_obj_context_subj.txt","matrices_1160_arg_subj_context_obj.txt"],[0.9,0.1]],set1,[1])

In [4]:
file_list1 = [objsubset1,subobjset1,obj08sub02set1,obj09sub01set1]

In [8]:
output = []
for a in file_list1:
    output.append([mf.averaged_product(simdict,'HYPER/HYPONYMS',a,"std_dev"),mf.averaged_product(simdict,'COHYPONYMS',a,"std_dev")])
output

[[[0.12819513814742128, 0.5071554695289946],
  [0.18283011891159115, 0.4875770015152735]],
 [[0.12538794135946613, 0.5024734689765858],
  [0.240215784303051, 0.5059754138407245]],
 [[0.13413771448778683, 0.5014386364259339],
  [0.193787209750406, 0.4717811907126341]],
 [[0.1302268730352817, 0.5047809468546545],
  [0.1865230024425557, 0.47703140544767303]]]

# linear (2) + quadratic (11) + cubic (8) + quartic(2)  (23 total)

In [5]:
# Make observables object
set2 = mf.observables(["Linear.txt","Quadratic.txt","Cubic1.txt","Quartic1.txt"])
# Load matrices and make vector dictionaries
objsubset2 = mf.vector_dictionary("matrices_1160_arg_obj_context_subj.txt",set2)
subobjset2 = mf.vector_dictionary("matrices_1160_arg_subj_context_obj.txt",set2,[0])
obj08sub02set2 = mf.vector_dictionary([["matrices_1160_arg_obj_context_subj.txt","matrices_1160_arg_subj_context_obj.txt"],[0.8,0.2]],set2,[1])
obj09sub01set2 = mf.vector_dictionary([["matrices_1160_arg_obj_context_subj.txt","matrices_1160_arg_subj_context_obj.txt"],[0.9,0.1]],set2,[1])

In [6]:
file_list2 = [objsubset2,subobjset2,obj08sub02set2,obj09sub01set2]

In [12]:
output = []
for a in file_list2:
    output.append([mf.averaged_product(simdict,'HYPER/HYPONYMS',a,"std_dev"),mf.averaged_product(simdict,'COHYPONYMS',a,"std_dev")])
output

[[[0.13162707768360712, 0.46973844850325025],
  [0.1920150917651739, 0.4610064765067929]],
 [[0.13409498011344806, 0.47489563899347476],
  [0.24883271598637713, 0.48780756186034546]],
 [[0.13569691122824282, 0.4649463692653508],
  [0.2011622155417129, 0.45144925195567226]],
 [[0.1323974052602255, 0.4669096371470686],
  [0.19587510916161896, 0.4535851441530613]]]

In [22]:
len(mf.averaged_product_list(simdict,'COHYPONYMS',objsubset2,"std_dev"))

190

# Linear (2) + quadratic (11) + cubic (8) + quartic(2) + additional cubic and quartic (5) (28 total)

In [7]:
# Make observables object
set5 = mf.observables(["Linear.txt","Quadratic.txt","Cubic1.txt","Quartic1.txt","Additional1.txt"])
# Load matrices and make vector dictionaries
objsubset5 = mf.vector_dictionary("matrices_1160_arg_obj_context_subj.txt",set5)
subobjset5 = mf.vector_dictionary("matrices_1160_arg_subj_context_obj.txt",set5,[0])
obj08sub02set5 = mf.vector_dictionary([["matrices_1160_arg_obj_context_subj.txt","matrices_1160_arg_subj_context_obj.txt"],[0.8,0.2]],set5,[1])
obj09sub01set5 = mf.vector_dictionary([["matrices_1160_arg_obj_context_subj.txt","matrices_1160_arg_subj_context_obj.txt"],[0.9,0.1]],set5,[1])

In [8]:
file_list5 = [objsubset5,subobjset5,obj08sub02set5,obj09sub01set5]

In [19]:
output = []
for a in file_list5:
    output.append([mf.averaged_product(simdict,'HYPER/HYPONYMS',a,"std_dev"),mf.averaged_product(simdict,'COHYPONYMS',a,"std_dev")])
output

[[[0.133299760494055, 0.4588170772144774],
  [0.20377438501264636, 0.4530870300342831]],
 [[0.13904167569765882, 0.46937113288585547],
  [0.25593326887468926, 0.4842001288953564]],
 [[0.14087734413300423, 0.4575093618111323],
  [0.2089174227031328, 0.4517869568158021]],
 [[0.13644245116332462, 0.45804412047494086],
  [0.20420227553796666, 0.4501316317396267]]]

# Precision testing

## Some definitions

In [9]:
def exp1(file_name):
    #Using observable vectors with cosine distance

    #Compute the mean and the standard deviation for the SYNONYMS
    syn1 = mf.averaged_product(simdict,'COHYPONYMS',file_name,"std_dev")

    #Compute the mean and the standard deviation for the ANTONYMS
    ant1 = mf.averaged_product(simdict,'HYPER/HYPONYMS',file_name,"std_dev")
    
    #Use the means and deviations to set the divide between synonyms and antonyms
    divide1 = ant1[0] + ant1[1]/syn1[1] * (syn1[0]-ant1[0])/2
    
    # Use the earlier defined function to compute the list of scalar products of the verbs and compare with divide
    prodlist1 = mf.averaged_product_list(simdict,'COHYPONYMS',file_name,"std_dev")

    prodlist5 = mf.averaged_product_list(simdict,'HYPER/HYPONYMS',file_name,"std_dev")
    
    # Compare and count the number of synonyms we get right
    syncomparison1 = [a > divide1 for a in list(prodlist1.values())]

    # Compare and count the number of antonyms we get right
    antcomparison1 = [a < divide1 for a in list(prodlist5.values())]

    #Compute the average precision
    precision1 = (syncomparison1.count(True) + antcomparison1.count(True))/(len(syncomparison1) + len(antcomparison1))
    
    return precision1

In [10]:
def exp2(file_name,myseed1,myseed2,samplesize1,samplesize2):
    #Since here we use just a subset of the pairs of synonyms and antonyms to determine the means and deviation, we have to do this by hand

    #Compute the products for all the observable deviation vectors associated to the SYNONYMS pairs
    all1 = mf.averaged_product_list(simdict,'COHYPONYMS',file_name,"std_dev")

    #The subset from which we copute the means is randomly selected, we seed the random generator for repeatable results. Chosen seed 7
    random.seed(myseed1)

    mysample = random.sample(list(all1),samplesize1)

    #Find complementary sample where we will predict and test
    mycomplsample = set(all1.keys()) - set(mysample)

    #Compute the means and standard deviations
    syn1 = [np.mean(np.array(list(map(all1.get,mysample)))),np.std(np.array(list(map(all1.get,mysample))))]

    #Now the same thing for the antonyms

    #Compute the products for all the observable deviation vectors associated to the SYNONYMS pairs
    all5 = mf.averaged_product_list(simdict,'HYPER/HYPONYMS',file_name,"std_dev")

    #The subset from which we copute the means is randomly selected, we seed the random generator for repeatable results. Chosen seed 13
    #random.seed(117) #Interesting values come out for this seed
    random.seed(myseed2)

    mysample2 = random.sample(list(all5),samplesize2)

    #Find complementary sample where we will predict and test
    mycomplsample2 = set(all5.keys()) - set(mysample2)

    #Compute the means and standard deviations
    ant1 = [np.mean(np.array(list(map(all5.get,mysample2)))),np.std(np.array(list(map(all5.get,mysample2))))]

    #Use the means and deviations to set the divide between synonyms and antonyms
    divide1 = ant1[0] + ant1[1]/syn1[1] * (syn1[0]-ant1[0])/2
    
    # Next we test on the complementary sample
    # Compare and count the number of synonyms we get right
    syncomparison1 = [a > divide1 for a in list(map(all1.get,mycomplsample))]

    # Compare and count the number of antonyms we get right
    antcomparison1 = [a < divide1 for a in list(map(all5.get,mycomplsample2))]

    #Compute the average precision
    precision1 = (syncomparison1.count(True) + antcomparison1.count(True))/(len(syncomparison1) + len(antcomparison1))

    return precision1

In [11]:
#Experiment 2 requires averaging over a number of different random samples. To generate these in a way 
#which is random but repeatable we need a list of seeds for the random generator. We decided to pick 20 samples

#seed the random generator before genearting the integer seeds for the random samples
random.seed(7)

seed_list = [(random.randint(0,5000),random.randint(0,5000)) for a in range(20)]

#Make a second seed_list for when we need 3 seeds instead of 2

seed_list2 = [(random.randint(0,5000),random.randint(0,5000),random.randint(0,5000)) for a in range(20)]

## 13 obs

In [20]:
# Experiment 1 synonym vs antonym
[exp1(a) for a in file_list1]

[0.5141414141414141,
 0.5363636363636364,
 0.5171717171717172,
 0.5151515151515151]

In [38]:
# Apply the function to every file with the given seed and average. The averaging is done using pure functions
# (lambda) so to compute all the precisions only once

# Synonyms vs Antonyms, sample size roughly 60%

(lambda x1 : [np.mean(x1,axis = 0),np.std(x1,axis=0)])([[exp2(myfile,*a,124,520) for myfile in file_list1] for a in seed_list ])

[array([0.51184971, 0.53193642, 0.52023121, 0.51618497]),
 array([0.02686307, 0.01641239, 0.02522908, 0.02495276])]

In [39]:
# Synonyms vs Antonyms, sample size roughly 10%

(lambda x1 : [np.mean(x1,axis = 0),np.std(x1,axis=0)])([[exp2(myfile,*a,19,80) for myfile in file_list1] for a in seed_list ])

[array([0.50909091, 0.5462963 , 0.51481481, 0.51503928]),
 array([0.01663328, 0.01627917, 0.01976743, 0.01754184])]

In [42]:
# Synonyms vs Antonyms, sample size roughly 5%

(lambda x1 : [np.mean(x1,axis = 0),np.std(x1,axis=0)])([[exp2(myfile,*a,9,40) for myfile in file_list1] for a in seed_list ])

[array([0.51089267, 0.54612115, 0.51312434, 0.51376196]),
 array([0.02853278, 0.02947702, 0.03721766, 0.03161325])]

In [43]:
# Synonyms vs Antonyms, sample size 5

(lambda x1 : [np.mean(x1,axis = 0),np.std(x1,axis=0)])([[exp2(myfile,*a,5,5) for myfile in file_list1] for a in seed_list ])

[array([0.53607143, 0.57091837, 0.53408163, 0.53408163]),
 array([0.03957194, 0.04450606, 0.04814597, 0.0426091 ])]

## 23 obs

In [24]:
# Experiment 1 synonym vs antonym
[exp1(a) for a in file_list2]

[0.5252525252525253,
 0.5565656565656566,
 0.5303030303030303,
 0.5444444444444444]

In [37]:
# Apply the function to every file with the given seed and average. The averaging is done using pure functions
# (lambda) so to compute all the precisions only once

# Synonyms vs Antonyms, sample size roughly 60%

(lambda x1 : [np.mean(x1,axis = 0),np.std(x1,axis=0)])([[exp2(myfile,*a,124,520) for myfile in file_list2] for a in seed_list ])

[array([0.52254335, 0.55274566, 0.53424855, 0.54277457]),
 array([0.02398322, 0.01461968, 0.02143946, 0.02087338])]

In [40]:
# Synonyms vs Antonyms, sample size roughly 10%

(lambda x1 : [np.mean(x1,axis = 0),np.std(x1,axis=0)])([[exp2(myfile,*a,19,80) for myfile in file_list2] for a in seed_list ])

[array([0.52160494, 0.56380471, 0.53237935, 0.53271605]),
 array([0.01997905, 0.01981572, 0.02234904, 0.02282309])]

In [44]:
# Synonyms vs Antonyms, sample size roughly 5%

(lambda x1 : [np.mean(x1,axis = 0),np.std(x1,axis=0)])([[exp2(myfile,*a,9,40) for myfile in file_list2] for a in seed_list ])

[array([0.52252922, 0.56280553, 0.52672689, 0.5293305 ]),
 array([0.03738693, 0.03022142, 0.04436598, 0.04274099])]

In [45]:
# Synonyms vs Antonyms, sample size 5

(lambda x1 : [np.mean(x1,axis = 0),np.std(x1,axis=0)])([[exp2(myfile,*a,5,5) for myfile in file_list2] for a in seed_list ])

[array([0.54663265, 0.58535714, 0.54255102, 0.54653061]),
 array([0.04184806, 0.04101263, 0.04726495, 0.04487755])]

## 28 obs

In [26]:
# Experiment 1 synonym vs antonym
[exp1(a) for a in file_list5]

[0.5353535353535354,
 0.5606060606060606,
 0.5383838383838384,
 0.5525252525252525]

In [36]:
# Apply the function to every file with the given seed and average. The averaging is done using pure functions
# (lambda) so to compute all the precisions only once

# Synonyms vs Antonyms, sample size roughly 60%

(lambda x1 : [np.mean(x1,axis = 0),np.std(x1,axis=0)])([[exp2(myfile,*a,124,520) for myfile in file_list5] for a in seed_list ])

[array([0.53598266, 0.55895954, 0.53612717, 0.55057803]),
 array([0.02481976, 0.01341364, 0.0201381 , 0.02024153])]

In [41]:
# Synonyms vs Antonyms, sample size roughly 10%

(lambda x1 : [np.mean(x1,axis = 0),np.std(x1,axis=0)])([[exp2(myfile,*a,19,80) for myfile in file_list5] for a in seed_list ])

[array([0.53131313, 0.56571268, 0.53810325, 0.53765432]),
 array([0.02476878, 0.01919315, 0.02453649, 0.02524248])]

In [46]:
# Synonyms vs Antonyms, sample size roughly 5%

(lambda x1 : [np.mean(x1,axis = 0),np.std(x1,axis=0)])([[exp2(myfile,*a,9,40) for myfile in file_list5] for a in seed_list ])

[array([0.53108395, 0.56546227, 0.53113709, 0.53310308]),
 array([0.04190442, 0.02993135, 0.04919574, 0.0445121 ])]

In [47]:
# Synonyms vs Antonyms, sample size 5

(lambda x1 : [np.mean(x1,axis = 0),np.std(x1,axis=0)])([[exp2(myfile,*a,5,5) for myfile in file_list5] for a in seed_list ])

[array([0.55096939, 0.58408163, 0.54857143, 0.54872449]),
 array([0.04231247, 0.03861729, 0.04705996, 0.04190372])]

In [62]:
# Synonyms vs Antonyms, sample size 5

(lambda x1 : [np.mean(x1,axis = 0),np.std(x1,axis=0)])([[exp2(myfile,*a,10,10) for myfile in file_list5] for a in seed_list ])

[array([0.53505155, 0.56840206, 0.53350515, 0.53613402]),
 array([0.04266597, 0.03820735, 0.04794701, 0.04352845])]

## Precision on human judgment

In [48]:
#First extract the largest value and use it to normalise the rest
allvals=np.array([])
for a in simdict.keys():
    allvals = np.concatenate((allvals,np.array(simdict[a]).T[2]))
allvals = np.array([float(a) for a in allvals])
highest = max(allvals)
highest

9.96

In [49]:
#Extract all values for the synonym pairs and normalise
allsyn =np.array([float(a) for a in np.array(simdict['COHYPONYMS']).T[2]])
allsyn = allsyn / highest
#Same for anotnysm
allant =np.array([float(a) for a in np.array(simdict['HYPER/HYPONYMS']).T[2]])
allant = allant / highest

In [52]:
# Compute mean and deviations
syn1 = [np.mean(allsyn),np.std(allsyn)]
ant1 = [np.mean(allant),np.std(allant)]
print(syn1,ant1)

[0.4453339674487423, 0.23852562050825882] [0.6036671686746988, 0.21116678615197718]


In [54]:
#Use the means and deviations to set the divide between synonyms and antonyms
divide1 = ant1[0] + ant1[1]/syn1[1] * (syn1[0]-ant1[0])/2

# Compare and count the number of synonyms we get right
syncomparison1 = [a > divide1 for a in allsyn]

# Compare and count the number of antonyms we get right
antcomparison1 = [a < divide1 for a in allant]

precision1 = (syncomparison1.count(True) + antcomparison1.count(True))/(len(syncomparison1) + len(antcomparison1))

print(divide1)
print(precision1)

0.5335809591245556
0.3686868686868687


In [55]:
# We define similar functions as previously but we needed some tweeked input

allsyndict = {}
for a in simdict['COHYPONYMS']:
    allsyndict.update({(a[0],a[1]):a[2]/highest})
    
allantdict = {}
for a in simdict['HYPER/HYPONYMS']:
    allantdict.update({(a[0],a[1]):a[2]/highest})

In [56]:
def human1(myseed1,myseed2,samplesize1,samplesize2):
    
    #Compute the products for all the observable deviation vectors associated to the SYNONYMS pairs
    all1 = allsyndict

    #The subset from which we copute the means is randomly selected, we seed the random generator for repeatable results. Chosen seed 7
    random.seed(myseed1)

    mysample = random.sample(list(all1),samplesize1)

    #Find complementary sample where we will predict and test
    mycomplsample = set(all1.keys()) - set(mysample)

    #Compute the means and standard deviations
    syn1 = [np.mean(np.array(list(map(all1.get,mysample)))),np.std(np.array(list(map(all1.get,mysample))))]

    #Now the same thing for the antonyms

    #Compute the products for all the observable deviation vectors associated to the SYNONYMS pairs
    all5 = allantdict

    #The subset from which we copute the means is randomly selected, we seed the random generator for repeatable results. Chosen seed 13
    #random.seed(117) #Interesting values come out for this seed
    random.seed(myseed2)

    mysample2 = random.sample(list(all5),samplesize2)

    #Find complementary sample where we will predict and test
    mycomplsample2 = set(all5.keys()) - set(mysample2)

    #Compute the means and standard deviations
    ant1 = [np.mean(np.array(list(map(all5.get,mysample2)))),np.std(np.array(list(map(all5.get,mysample2))))]

    #Use the means and deviations to set the divide between synonyms and antonyms
    divide1 = ant1[0] + ant1[1]/syn1[1] * (syn1[0]-ant1[0])/2
    
    # Next we test on the complementary sample
    # Compare and count the number of synonyms we get right
    syncomparison1 = [a > divide1 for a in list(map(all1.get,mycomplsample))]

    # Compare and count the number of antonyms we get right
    antcomparison1 = [a < divide1 for a in list(map(all5.get,mycomplsample2))]

    #Compute the average precision
    precision1 = (syncomparison1.count(True) + antcomparison1.count(True))/(len(syncomparison1) + len(antcomparison1))

    return precision1

In [57]:
# Apply the function to every file with the given seed and average. The averaging is done using pure functions
# (lambda) so to compute all the precisions only once

# Synonyms vs Antonyms, sample size roughly 60%

(lambda x1 : [np.mean(x1,axis = 0),np.std(x1,axis=0)])([human1(*a,124,520) for a in seed_list ])

[0.3611271676300578, 0.01773339844554187]

## Length of hypernyms vs hyponyms

In [12]:
# Import the natural language processing libraries
#import nltk
from nltk.corpus import wordnet as wn

In [13]:
# Function to extract all the hyponyms of a given string
def get_hyponyms(synset):
    hyponyms = set()
    for hyponym in synset.hyponyms():
        hyponyms |= set(get_hyponyms(hyponym))
    return hyponyms | set(synset.hyponyms())

In [14]:
# Function to test whether the second word is a hyponym of the first
def is_hyponym(hyper,hypo):
    
    #Extract all possible meanings of the given hyper string
    allsyn = wn.synsets(hyper)
    
    # Initialise allhyponyms var to empty set
    allhypo = set()
    
    #Loop over all the possible meanings of hyper, thus allsyn, and search for all the associated hyponyms
    for syn in allsyn:
        allhypo |= get_hyponyms(syn)
    
    #Check if the given hypo has any overlap with the set of hyponyms found
    return allhypo.intersection(set(wn.synsets(hypo))) != set()

### Playing around with wordnet

In [14]:
wn.synsets('fruit')

[Synset('fruit.n.01'),
 Synset('yield.n.03'),
 Synset('fruit.n.03'),
 Synset('fruit.v.01'),
 Synset('fruit.v.02')]

In [53]:
wn.synsets('fruit')[1].definition()

'an amount of a product'

In [16]:
wn.synsets('fruit')[0].hyponyms()

[Synset('accessory_fruit.n.01'),
 Synset('achene.n.01'),
 Synset('acorn.n.01'),
 Synset('aggregate_fruit.n.01'),
 Synset('berry.n.02'),
 Synset('buckthorn_berry.n.01'),
 Synset('buffalo_nut.n.01'),
 Synset('chokecherry.n.01'),
 Synset('cubeb.n.01'),
 Synset('drupe.n.01'),
 Synset('ear.n.05'),
 Synset('edible_fruit.n.01'),
 Synset('fruitlet.n.01'),
 Synset('gourd.n.02'),
 Synset('hagberry.n.01'),
 Synset('hip.n.05'),
 Synset('juniper_berry.n.01'),
 Synset('marasca.n.01'),
 Synset('may_apple.n.01'),
 Synset('olive.n.01'),
 Synset('pod.n.02'),
 Synset('pome.n.01'),
 Synset('prairie_gourd.n.01'),
 Synset('pyxidium.n.01'),
 Synset('quandong.n.02'),
 Synset('rowanberry.n.01'),
 Synset('schizocarp.n.01'),
 Synset('seed.n.01'),
 Synset('wild_cherry.n.01')]

In [25]:
wn.synsets('go')

[Synset('go.n.01'),
 Synset('adam.n.03'),
 Synset('crack.n.09'),
 Synset('go.n.04'),
 Synset('travel.v.01'),
 Synset('go.v.02'),
 Synset('go.v.03'),
 Synset('become.v.01'),
 Synset('go.v.05'),
 Synset('run.v.05'),
 Synset('run.v.03'),
 Synset('proceed.v.04'),
 Synset('go.v.09'),
 Synset('go.v.10'),
 Synset('sound.v.02'),
 Synset('function.v.01'),
 Synset('run_low.v.01'),
 Synset('move.v.13'),
 Synset('survive.v.01'),
 Synset('go.v.16'),
 Synset('die.v.01'),
 Synset('belong.v.03'),
 Synset('go.v.19'),
 Synset('start.v.09'),
 Synset('move.v.15'),
 Synset('go.v.22'),
 Synset('go.v.23'),
 Synset('blend.v.02'),
 Synset('go.v.25'),
 Synset('fit.v.02'),
 Synset('rifle.v.02'),
 Synset('go.v.28'),
 Synset('plump.v.04'),
 Synset('fail.v.04'),
 Synset('go.a.01')]

In [27]:
wn.synsets('go')[6].definition()

'move away from a place into another direction'

In [28]:
wn.synsets('go')[6].hyponyms()

[Synset('shove_off.v.01')]

In [29]:
simdict['HYPER/HYPONYMS']

[['calculate', 'add', 5.98],
 ['pardon', 'forgive', 8.96],
 ['smell', 'sniff', 7.97],
 ['replace', 'move', 1.49],
 ['rationalize', 'argue', 4.48],
 ['descend', 'go', 3.32],
 ['feel', 'touch', 7.8],
 ['decay', 'deteriorate', 8.13],
 ['protect', 'defend', 7.8],
 ['build', 'grow', 4.81],
 ['cover', 'protect', 6.81],
 ['defeat', 'beat', 8.47],
 ['go', 'advance', 6.64],
 ['produce', 'reproduce', 5.98],
 ['shake', 'shiver', 6.31],
 ['take', 'carry', 5.64],
 ['accomplish', 'succeed', 8.3],
 ['drive', 'operate', 4.98],
 ['ask', 'tell', 0.66],
 ['gather', 'reap', 5.98],
 ['kill', 'shoot', 5.31],
 ['crunch', 'chew', 6.47],
 ['hurt', 'smash', 4.65],
 ['cook', 'bake', 7.8],
 ['break', 'destroy', 8.3],
 ['put', 'take', 1.49],
 ['hitch', 'ride', 4.48],
 ['destroy', 'kill', 7.8],
 ['obtain', 'get', 9.3],
 ['deposit', 'put', 6.47],
 ['jump', 'climb', 1.99],
 ['look', 'examine', 8.3],
 ['delay', 'pause', 8.13],
 ['take', 'use', 3.15],
 ['beat', 'kill', 3.65],
 ['think', 'presume', 3.49],
 ['tend', 'hel

In [37]:
wn.synsets('calculate')

[Synset('calculate.v.01'),
 Synset('calculate.v.02'),
 Synset('account.v.02'),
 Synset('forecast.v.01'),
 Synset('calculate.v.05'),
 Synset('count.v.08')]

In [38]:
get_hyponyms(wn.synset('calculate.v.01'))

{Synset('add.v.04'),
 Synset('assess.v.04'),
 Synset('average.v.03'),
 Synset('budget.v.01'),
 Synset('capitalize.v.04'),
 Synset('carry_back.v.01'),
 Synset('cube.v.01'),
 Synset('differentiate.v.03'),
 Synset('divide.v.02'),
 Synset('estimate.v.01'),
 Synset('extract.v.08'),
 Synset('factor.v.01'),
 Synset('factorize.v.01'),
 Synset('foot.v.03'),
 Synset('give.v.27'),
 Synset('guesstimate.v.01'),
 Synset('halve.v.01'),
 Synset('integrate.v.04'),
 Synset('interpolate.v.01'),
 Synset('lowball.v.01'),
 Synset('make.v.44'),
 Synset('miscalculate.v.02'),
 Synset('misgauge.v.01'),
 Synset('multiply.v.01'),
 Synset('overcapitalize.v.01'),
 Synset('place.v.11'),
 Synset('process.v.03'),
 Synset('prorate.v.02'),
 Synset('quantize.v.01'),
 Synset('quantize.v.02'),
 Synset('quarter.v.04'),
 Synset('raise.v.23'),
 Synset('recalculate.v.01'),
 Synset('reckon.v.06'),
 Synset('resolve.v.06'),
 Synset('square.v.02'),
 Synset('subtract.v.01'),
 Synset('survey.v.06'),
 Synset('triangulate.v.03'),
 Syn

In [39]:
wn.synsets('add')

[Synset('attention_deficit_disorder.n.01'),
 Synset('add.v.01'),
 Synset('add.v.02'),
 Synset('lend.v.01'),
 Synset('add.v.04'),
 Synset('total.v.02'),
 Synset('add.v.06')]

In [32]:
is_hyponym('calculate','add')

True

In [16]:
is_hyponym('add','calculate')

False

## Testing the lengths

In [69]:
pairlist = [list(a) for a in np.array(simdict['HYPER/HYPONYMS']).T[:2].T]

In [156]:
# Compare the lengths, how often is the hyper smaller than the hypo? Deviation vectors
compare = []
for a in pairlist[:243]+pairlist[250:515]+pairlist[550:800]:
    local = [mf.M_vec_mult_dev(objsubset5[a[0]].val,objsubset5[a[0]].val,objsubset5.mean,objsubset5.std),mf.M_vec_mult_dev(objsubset5[a[1]].val,objsubset5[a[1]].val,objsubset5.mean,objsubset5.std)]
    
    if is_hyponym(a[0],a[1]):
        compare.append(local[0]<local[1])
    else :
        compare.append(local[0]>local[1])
print(len(compare))
compare.count(True)/len(compare)

758


0.3733509234828496

In [98]:
len(pairlist)

800

In [157]:
# Normalised observable vectors
compare = []
for a in pairlist[:243]+pairlist[250:515]+pairlist[550:800]:
    local = [mf.M_vec_mult(objsubset5[a[0]].val,objsubset5[a[0]].val,objsubset5.mean_sqr),mf.M_vec_mult(objsubset5[a[1]].val,objsubset5[a[1]].val,objsubset5.mean_sqr)]
    
    if is_hyponym(a[0],a[1]):
        compare.append(local[0]<local[1])
    else :
        compare.append(local[0]>local[1])
compare.count(True)/len(compare)

0.32717678100263853

In [117]:
#pairlist[243]

['keep', 'save']

In [122]:
#test = wn.synsets('keep')
#len(test)

25

In [140]:
# The word restrain has among its hyponyms inhibit, which has among its hyponyms restrain, which leads to an infinte loop
#print(test[16])
#print(test[16].hyponyms())
#print(test[16].hyponyms()[3].hyponyms())

Synset('restrain.v.01')
[Synset('confine.v.03'), Synset('control.v.02'), Synset('hold.v.36'), Synset('inhibit.v.04')]
[Synset('choke.v.07'), Synset('quench.v.03'), Synset('restrain.v.01')]


### Testing high vs low node

In [17]:
# Make observables object
set6 = mf.observables(["HighNode.txt"])
# Load matrices and make vector dictionaries
objsubset6 = mf.vector_dictionary("matrices_1160_arg_obj_context_subj.txt",set6)
subobjset6 = mf.vector_dictionary("matrices_1160_arg_subj_context_obj.txt",set6,[0])
obj08sub02set6 = mf.vector_dictionary([["matrices_1160_arg_obj_context_subj.txt","matrices_1160_arg_subj_context_obj.txt"],[0.8,0.2]],set6,[1])
obj09sub01set6 = mf.vector_dictionary([["matrices_1160_arg_obj_context_subj.txt","matrices_1160_arg_subj_context_obj.txt"],[0.9,0.1]],set6,[1])

In [18]:
# Make observables object
set7 = mf.observables(["LowNode.txt"])
# Load matrices and make vector dictionaries
objsubset7 = mf.vector_dictionary("matrices_1160_arg_obj_context_subj.txt",set7)
subobjset4 = mf.vector_dictionary("matrices_1160_arg_subj_context_obj.txt",set7,[0])
obj08sub02set7 = mf.vector_dictionary([["matrices_1160_arg_obj_context_subj.txt","matrices_1160_arg_subj_context_obj.txt"],[0.8,0.2]],set7,[1])
obj09sub01set7 = mf.vector_dictionary([["matrices_1160_arg_obj_context_subj.txt","matrices_1160_arg_subj_context_obj.txt"],[0.9,0.1]],set7,[1])

In [160]:
pairlist = [list(a) for a in np.array(simdict['HYPER/HYPONYMS']).T[:2].T]

In [161]:
#High Node
# Compare the lengths, how often is the hyper smaller than the hypo? Deviation vectors
compare = []
for a in pairlist[:243]+pairlist[250:515]+pairlist[550:800]:
    local = [mf.M_vec_mult_dev(objsubset6[a[0]].val,objsubset6[a[0]].val,objsubset6.mean,objsubset6.std),mf.M_vec_mult_dev(objsubset6[a[1]].val,objsubset6[a[1]].val,objsubset6.mean,objsubset6.std)]
    
    if is_hyponym(a[0],a[1]):
        compare.append(local[0]<local[1])
    else :
        compare.append(local[0]>local[1])
print(len(compare))
compare.count(True)/len(compare)

758


0.39841688654353563

In [162]:
# Compare the lengths, how often is the hyper smaller than the hypo? Deviation vectors
compare = []
for a in pairlist[:243]+pairlist[250:515]+pairlist[550:800]:
    local = [mf.M_vec_mult_dev(objsubset7[a[0]].val,objsubset7[a[0]].val,objsubset7.mean,objsubset7.std),mf.M_vec_mult_dev(objsubset7[a[1]].val,objsubset7[a[1]].val,objsubset7.mean,objsubset7.std)]
    
    if is_hyponym(a[0],a[1]):
        compare.append(local[0]<local[1])
    else :
        compare.append(local[0]>local[1])
print(len(compare))
compare.count(True)/len(compare)

758


0.370712401055409

### Precision on prediction of Hyper/Hypo

In [163]:
pairlist = [list(a) for a in np.array(simdict['HYPER/HYPONYMS']).T[:2].T]

In [177]:
# Precision of predicting which are the hypo/hyper
compare = []
for a in pairlist[:243]+pairlist[250:515]+pairlist[550:800]:
    local = [mf.M_vec_mult_dev(objsubset5[a[0]].val,objsubset5[a[0]].val,objsubset5.mean,objsubset5.std),mf.M_vec_mult_dev(objsubset5[a[1]].val,objsubset5[a[1]].val,objsubset5.mean,objsubset5.std)]
    
    if is_hyponym(a[0],a[1]):
        compare.append(local)
    else :
        compare.append([local[1],local[0]])
mymean = np.mean(np.array(compare),axis = 0)
mystd = np.std(np.array(compare),axis = 0)
print(mymean)
print(mystd)
mydivide = mymean[1] + mystd[1]/mystd[0] * (mymean[0]-mymean[1])/2
print(mydivide)
myprecision = []
for a in compare:
    myprecision.append(a[0] > mydivide)
    myprecision.append(a[1] < mydivide)
myprecision.count(True)/len(myprecision)

[78.51704634 39.38844643]
[246.77285905 148.38009907]
51.15210949028466


0.5560686015831134

In [169]:
compare

[[5.23461715148488, 73.0910399737601],
 [3.0268293053672295, 2.960775001076481],
 [2.2913009821966495, 2.4642368384772575],
 [15.365119301759123, 31.226639444476643],
 [16.545574850818117, 2.967707953487911],
 [94.86775599632743, 2.201936752437856],
 [2.2184023057198727, 3.569018935956074],
 [3.585210362566973, 2.35662166935],
 [11.05370455011977, 4.9488278824471434],
 [6.04220899676834, 101.82016109471029],
 [11.05370455011977, 259.2123929632238],
 [3.5378761149824984, 12.955581206888283],
 [94.86775599632743, 2.448320298401484],
 [103.00506102105467, 38.26927825250708],
 [2.4698257207143284, 2.964259546677599],
 [691.0159504470498, 128.14042086139486],
 [1.7387716941604578, 2.2668951716880823],
 [32.39620136802295, 13.246644920327386],
 [57.02675940015975, 92.74349899393941],
 [10.330871804593787, 2.7507147212736838],
 [37.16139000612645, 4.213037439709207],
 [3.9012033578759198, 3.902308003010446],
 [1.7118853825662208, 3.4830773636805032],
 [3.74025094942773, 3.955980163903381],
 [

In [172]:
# Compare the lengths, how often is the hyper smaller than the hypo? Deviation vectors
compare = []
for a in pairlist[:243]+pairlist[250:515]+pairlist[550:800]:
    local = [mf.M_vec_mult_dev(objsubset5[a[0]].val,objsubset5[a[0]].val,objsubset5.mean,objsubset5.std),mf.M_vec_mult_dev(objsubset5[a[1]].val,objsubset5[a[1]].val,objsubset5.mean,objsubset5.std)]
    
    if is_hyponym(a[0],a[1]):
        compare.append(local)
    else :
        compare.append([local[1],local[0]])
    if local[0]>200 or local[1]>200:
        print([a,local])

[['cover', 'protect'], [259.2123929632238, 11.05370455011977]]
[['take', 'carry'], [691.0159504470498, 128.14042086139486]]
[['put', 'take'], [39.983185256724994, 691.0159504470498]]
[['obtain', 'get'], [13.819327637581965, 500.97410476861023]]
[['take', 'use'], [691.0159504470498, 285.31386284690575]]
[['take', 'acquire'], [691.0159504470498, 11.179055607324322]]
[['get', 'grab'], [500.97410476861023, 2.5559765702232555]]
[['kidnap', 'take'], [2.010669963442691, 691.0159504470498]]
[['accept', 'allow'], [252.74872462511308, 187.76342621503323]]
[['become', 'make'], [17.547683958352547, 808.1090066195932]]
[['begin', 'introduce'], [271.1124127011693, 78.88008537909472]]
[['make', 'compose'], [808.1090066195932, 2.7822389668592105]]
[['describe', 'write'], [369.4100486518224, 81.67390168039424]]
[['gain', 'get'], [40.639963120536784, 500.97410476861023]]
[['supply', 'give'], [7.427812739533539, 330.23448114918835]]
[['get', 'have'], [500.97410476861023, 2236.200124990689]]
[['make', 'de

In [28]:
allmyhypos = set()
for a in list(map(get_hyponyms,wn.synsets('have'))):
    allmyhypos = allmyhypos.union(a)
len(allmyhypos)

346

In [29]:
allmyhypos = set()
for a in list(map(get_hyponyms,wn.synsets('give'))):
    allmyhypos = allmyhypos.union(a)
len(allmyhypos)

477

In [30]:
allmyhypos = set()
for a in list(map(get_hyponyms,wn.synsets('include'))):
    allmyhypos = allmyhypos.union(a)
len(allmyhypos)

25